<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAIIfBR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAIIfBR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAIIfBR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAIIfBR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLAIIfBR\App_KernelDevDebugContainer([
    'container.build_hash' => 'LAIIfBR',
    'container.build_id' => '753ec324',
    'container.build_time' => 1695293419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAIIfBR');
